
# <p style="text-align: center;">MIS382: Advanced Predictive Modeling</p>
# <p style="text-align: center;">Assignment 5</p>
## <p style="text-align: center;">Total points: 35</p>
## <p style="text-align: center;">Due: Monday, November 27th, submitted via Canvas by 11:59 pm</p>

Your homework should be written in a **Jupyter notebook**. You may work in groups of two if you wish. Only one student per team needs to submit the assignment on Canvas.  But be sure to include name and UTID for both students.  Homework groups will be created and managed through Canvas, so please do not arbitrarily change your homework group.  

Also, please make sure your code runs and the graphics (and anything else) are displayed in your notebook before submitting. (%matplotlib inline)

# Question 1: Ensembles (1+12+2 = 15pts)
In this question, we will compare performance of different ensemble methods: [Random Forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), [Gradient Boosting Decision Tree](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html) (GBDT), and [XGBoost](http://xgboost.readthedocs.io/en/latest/).  Note that you have to install xgboost package in addition to scikit-learn.  You can see installation guides [here](http://xgboost.readthedocs.io/en/latest/build.html).




Two  datasets are provided for this problem. For **each of the datasets ((X1.csv, y1.csv), (X2.csv, y2.csv))**, do the following:

1. Load the data and partition it into features (X) and the target label (y) for classification task. Then, use [train_test_split](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html) to split data into training and testing: test_size=0.33, random_state=42.

2. Build a classifier using [Random Forest](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.RandomForestClassifier.html), [Gradient Boosting Decision Tree](http://scikit-learn.org/stable/modules/generated/sklearn.ensemble.GradientBoostingClassifier.html), and [XGBoost](http://xgboost.readthedocs.io/en/latest/), respectively, and answer the following for each classifier.

 - Mention any design choices (with reasoning/justification) that you made, e.g. the hyperparameters considered for each classifier.
 - Report the mean error rate (fraction of incorrect labels) and the confusion matrix on test data. <br>
 - Report the feature importance and time of execution (training and predicting times).

3. Compare the three classifiers for the two different datasets ((X1.csv, y1.csv), (X2.csv, y2.csv)) in terms of the misclassification rate.  What are the characteristics of the dataset and the classifiers that resulted in somewhat different comparative results?

In [3]:
import pandas as pd

In [1]:
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBClassifier
from time import time
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
%matplotlib inline

/Users/ReeceWooten/anaconda/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


## Solution

In [8]:
X1=pd.read_csv('/Users/ReeceWooten/Documents/School /MSBA/Fall/Adv.Predictive/hmk5_data/X1.csv',header=None)
X2=pd.read_csv('/Users/ReeceWooten/Documents/School /MSBA/Fall/Adv.Predictive/hmk5_data/X2.csv',header=None)
y1=pd.read_csv('/Users/ReeceWooten/Documents/School /MSBA/Fall/Adv.Predictive/hmk5_data/y1.csv',header=None)
y2=pd.read_csv('/Users/ReeceWooten/Documents/School /MSBA/Fall/Adv.Predictive/hmk5_data/y2.csv',header=None)

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X1, y1, test_size=0.33, random_state=42)

In [12]:
X2_train, X2_test, y2_train, y2_test = train_test_split(X2, y2, test_size=0.33, random_state=42)

# Random Forests

### (X1.csv, y1.csv)

In [96]:
from time import time
params={'n_estimators':[100,500,1000]}
random_for=RandomForestClassifier(n_jobs=-1,random_state=42)
clf=GridSearchCV(random_for, params)
fit=clf.fit(X=X_train,y=y_train.values.ravel())
pred=fit.predict(X_test)
print 'best Parameters:', fit.best_params_

best Parameters: {'n_estimators': 1000}


In [97]:
random_for=RandomForestClassifier(n_jobs=-1,random_state=42,n_estimators=1000)
t0=time()
fit=random_for.fit(X=X_train,y=y_train.values.ravel())
pred=fit.predict(X_test)
print 'Time Taken:',time()-t0
print 'Feature Importance:', fit.feature_importances_

Time Taken: 10.2630000114
Feature Importance: [ 0.04431502  0.01433167  0.01412465  0.01430413  0.01474061  0.01451441
  0.01504657  0.01522581  0.01404021  0.01448577  0.01478121  0.01413298
  0.01507971  0.01388314  0.01473862  0.01436213  0.01429501  0.01450129
  0.06266232  0.01430806  0.01482966  0.09657533  0.42067637  0.01417478
  0.01435882  0.01382586  0.01439905  0.01467517  0.01438618  0.01422543]


In [98]:
from sklearn.metrics import confusion_matrix
confus=confusion_matrix(y_pred=pred,y_true=y_test)
confus

array([[1433,  248],
       [ 152, 1467]])

In [99]:
print 'Mean Error Rate:',(confus[0][1]+confus[1][0])/float(len(y_test))

Mean Error Rate: 0.121212121212


### (X2.csv, y2.csv)

In [88]:
import timeit
params={'n_estimators':[100,500,1000]}
random_for=RandomForestClassifier(n_jobs=-1,random_state=42)
clf=GridSearchCV(random_for, params)
fit=clf.fit(X=X2_train,y=y2_train.values.ravel())
pred=fit.predict(X2_test)
print 'best Parameters:', fit.best_params_

best Parameters: {'n_estimators': 1000}


In [91]:
t0=time()
random_for=RandomForestClassifier(n_jobs=-1,random_state=42,n_estimators=1000)
fit=random_for.fit(X=X2_train,y=y2_train.values.ravel())
pred=fit.predict(X2_test)
print 'Time Taken:',time()-t0
print 'Feature Importance:', fit.feature_importances_

Feature Importance: [ 0.02896598  0.01699222  0.01619105  0.05564484  0.05335792  0.0591138
  0.04776768  0.056298    0.04464193  0.14732021  0.03613252  0.08334729
  0.01564104  0.06610192  0.01624294  0.06865922  0.05177554  0.0165388
  0.07981951  0.03944759]


In [93]:
from sklearn.metrics import confusion_matrix
confus=confusion_matrix(y_pred=pred,y_true=y2_test)
confus

array([[784,  66],
       [ 35, 765]])

In [94]:
print 'Mean Error Rate:',(confus[0][1]+confus[1][0])/float(len(y_test))

Mean Error Rate: 0.0306060606061


# Gradient Boosting

### (X1.csv, y1.csv)

In [103]:
import timeit
t0=time()
params={'max_depth':[1,2,3],'learning_rate':[.001,.01,.1],'n_estimators':[500,1000]}
grad=GradientBoostingClassifier(random_state=42)
clf=GridSearchCV(grad, params)
fit=clf.fit(X=X_train,y=y_train.values.ravel())
print 'Time Taken:',time()-t0
print 'best Parameters:', fit.best_params_

Time Taken: 313.991631031
best Parameters: {'n_estimators': 1000, 'learning_rate': 0.1, 'max_depth': 3}


In [104]:
t0=time()
grad1=GradientBoostingClassifier(max_depth=3,learning_rate=.1,n_estimators=1000)
fit=grad1.fit(X=X_train,y=y_train.values.ravel())
pred=fit.predict(X_test)
print 'Time Taken:',time()-t0
fit.feature_importances_

Time Taken: 15.3645939827


array([ 0.0544251 ,  0.01917306,  0.02850817,  0.0292458 ,  0.02901202,
        0.02837113,  0.03308446,  0.03630208,  0.02287203,  0.03131862,
        0.02270644,  0.02459479,  0.03241855,  0.02237735,  0.02996814,
        0.02395729,  0.02883544,  0.02663355,  0.05859324,  0.02359324,
        0.02788738,  0.07085674,  0.09011325,  0.02471198,  0.03253809,
        0.03168191,  0.02510279,  0.02526566,  0.02671365,  0.03913805])

In [105]:
from sklearn.metrics import confusion_matrix
confus=confusion_matrix(y_pred=pred,y_true=y_test)
confus


array([[1499,  182],
       [ 141, 1478]])

In [106]:
print 'Mean Error Rate:',(confus[0][1]+confus[1][0])/float(len(y2_test))

Mean Error Rate: 0.195757575758


### (X2.csv, y2.csv)

In [107]:
import timeit
t0=time()
params={'max_depth':[1,2,3],'learning_rate':[.001,.01,.1],'n_estimators':[500,1000]}
grad2=GradientBoostingClassifier(random_state=42)
clf2=GridSearchCV(grad2, params)
fit2=clf2.fit(X=X2_train,y=y2_train.values.ravel())
print 'Time Taken:',time()-t0
print 'best Parameters:', fit2.best_params_

Time Taken: 111.793998957
best Parameters: {'n_estimators': 1000, 'learning_rate': 0.1, 'max_depth': 3}


In [108]:
grad2=GradientBoostingClassifier(max_depth=3,learning_rate=.1,n_estimators=1000)
fit2=grad2.fit(X=X2_train,y=y2_train.values.ravel())
pred2=fit2.predict(X2_test)
fit2.feature_importances_

array([ 0.05122169,  0.03045946,  0.02431011,  0.06181678,  0.06379853,
        0.04765492,  0.04572279,  0.06876345,  0.04984366,  0.06439279,
        0.05048733,  0.06456411,  0.01997549,  0.05266167,  0.02340354,
        0.07135562,  0.05588212,  0.02688073,  0.07484439,  0.05196082])

In [109]:
from sklearn.metrics import confusion_matrix
confus2=confusion_matrix(y_pred=pred2,y_true=y2_test)
confus2

array([[789,  61],
       [ 32, 768]])

In [110]:
print 'Mean Error Rate:',(confus2[0][1]+confus2[1][0])/float(len(y2_test))

Mean Error Rate: 0.0563636363636


# XGBoost

### (X1.csv, y1.csv)

In [112]:
import timeit
t0=time()
params={'max_depth':[5,6,7],'min_child_weight':[1,2,3],'gamma':[0,1,2]}
grad3=XGBClassifier()
clf3=GridSearchCV(grad3, params)
fit3=clf3.fit(X=X_train,y=y_train.values.ravel())
print 'Time Taken:',time()-t0
print 'best Parameters:', fit3.best_params_

Time Taken: 108.996088028
best Parameters: {'max_depth': 7, 'gamma': 1, 'min_child_weight': 2}


In [114]:
t0=time()
model = XGBClassifier(max_depth=7,min_child_weight=2,gamma=1)
fit=model.fit(X_train, y_train.values.ravel())
pred=fit.predict(X_test)
print 'Time Taken:',time()-t0
fit.feature_importances_

Time Taken: 2.37207388878


array([ 0.12555929,  0.02516779,  0.01454139,  0.01957494,  0.02013423,
        0.01649888,  0.01649888,  0.02880313,  0.01482103,  0.01565995,
        0.0159396 ,  0.01845638,  0.02488814,  0.00978747,  0.01510067,
        0.0192953 ,  0.01621924,  0.02041387,  0.16219239,  0.01845638,
        0.02181208,  0.13422818,  0.0950783 ,  0.01677852,  0.01538031,
        0.01677852,  0.02376957,  0.02041387,  0.02097316,  0.01677852], dtype=float32)

In [115]:
from sklearn.metrics import confusion_matrix
confus=confusion_matrix(y_pred=pred,y_true=y_test)
confus

array([[1526,  155],
       [ 109, 1510]])

In [116]:
print 'Mean Error Rate:',(confus[0][1]+confus[1][0])/float(len(y_test))

Mean Error Rate: 0.08


### (X2.csv, y2.csv)

In [117]:
import timeit
t0=time()
params={'max_depth':[5,6,7],'min_child_weight':[1,2,3],'gamma':[0,1,2]}
grad3=XGBClassifier()
clf3=GridSearchCV(grad3, params)
fit3=clf3.fit(X=X2_train,y=y2_train.values.ravel())
print 'Time Taken:',time()-t0
print 'best Parameters:', fit3.best_params_

Time Taken: 37.8252789974
best Parameters: {'max_depth': 7, 'gamma': 0, 'min_child_weight': 1}


In [118]:
t0=time()
model = XGBClassifier(max_depth=7,min_child_weight=1,gamma=0)
fit=model.fit(X2_train, y2_train.values.ravel())
pred=fit.predict(X2_test)
print 'Time Taken:',time()-t0
fit.feature_importances_

Time Taken: 0.775943040848


array([ 0.04911092,  0.01714649,  0.01439458,  0.0607536 ,  0.06223539,
        0.06879763,  0.05546147,  0.06583404,  0.05609653,  0.0592718 ,
        0.0522862 ,  0.07281964,  0.01587638,  0.06710415,  0.01164268,
        0.07049111,  0.06456393,  0.01820491,  0.07006774,  0.04784081], dtype=float32)

In [120]:
from sklearn.metrics import confusion_matrix
confus=confusion_matrix(y_pred=pred,y_true=y2_test)
confus

array([[782,  68],
       [ 39, 761]])

In [121]:
print 'Mean Error Rate:',(confus[0][1]+confus[1][0])/float(len(y_test))

Mean Error Rate: 0.0324242424242


# Question 2: Visualization using Bokeh (10 pts)

In this problem, you'll build an interactive visualization. Bokeh is a Python interactive visualization library that targets modern web browsers for presentation. For more information on Bokeh, see http://bokeh.pydata.org/en/latest/. The problem statement is as follows:

Using the "nbasalariesfull.csv" data set from HMK4, your goal is to build a Bokeh visualization which allows the user to explore how salary (on a log scale) varies with points per game (PSG) and age. You will create a visualization that allows the user to toggle the X axis of a scatter plot between PSG and age, with the y-axis always being log Salary. Also add the hover tool so that if the user hovers over a datapoint in the plot a window pops up that shows the player name, team, position, salary, and the current x variable (PSG or age) depending on the current tab.  Color each point according to a player's position and provide a legend for the colors. Add the ability to Zoom in/out.  Add slight horizontal jitter to a player's age.

Hints: 
1. see: http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#basic-tooltips for hover and zoom tool examples.
2. See: http://bokeh.pydata.org/en/latest/docs/reference/plotting.html. Look for the scatter API.
3. See: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/styling.html#labels. For labeling axes.
4. See: https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html  for how to use jitter transform
5. See: http://bokeh.pydata.org/en/latest/docs/gallery/iris.html for coloring points by category
6. Use output_notebook() from Bokeh to output the plot to your notebook

Include an image screenshot in addition to the visualization output.

In [138]:
import warnings
warnings.filterwarnings('ignore')

import pandas as pd
import numpy as np
from bokeh.models.widgets import Panel, Tabs
from bokeh.models import CustomJS, ColumnDataSource, HoverTool, BoxZoomTool
from bokeh.models.transforms import Jitter
from bokeh.plotting import figure, output_notebook, show
from bokeh.core.properties import value
from bokeh.models import Legend,LegendItem

data = pd.read_csv("/Users/ReeceWooten/Documents/School /MSBA/Fall/Adv.Predictive/hmk5_data/nbasalariesfull.csv")
data["logsalary"] = data.SALARY.apply(np.log)

## Solution

1: Toggle x axis: PSG and age (check)

2: Hover over data point shows the player name, team, position, salary, and the current x variable (PSG or age)

3: Color each point according to a player's position and provide a legend for the colors

4: Add the ability to Zoom in/out

5: Add slight horizontal jitter to a player's age.


In [ ]:
source=data

In [7]:
data[:1]

Player   Tm Pos   Age     G    GS    MP    FG   FGA    FG%  \
0  Stephen Curry  GSW  PG  27.0  79.0  79.0  34.2  10.2  20.2  0.504   

     ...      DRB  TRB  AST  STL  BLK  TOV   PF   PSG    SALARY  logsalary  
0    ...      4.6  5.4  6.7  2.1  0.2  3.3  2.0  30.1  11370786  16.246558  

[1 rows x 31 columns]

In [54]:
pos_list=list(data['Pos'].value_counts().index)

In [154]:
# clears Figure history
from bokeh.io import curdoc
curdoc().clear()

In [155]:
source=ColumnDataSource(data)

hover = HoverTool(tooltips=[
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("Player", "@Player"),
    ("Team", "@Tm"),
    ("Position", "@Pos"),
    ("Salary", "@SALARY"),
])

hover2 = HoverTool(tooltips=[
    ("index", "@index"),
    ("(x,y)", "($x, $y)"),
    ("Player", "@Player"),
    ("Team", "@Tm"),
    ("Position", "@Pos"),
    ("Salary", "@SALARY"),
])


colormap = {'PF': 'red', 'PG': 'green', 'SF': 'blue','SG':'brown','C':'black','PF-C':'grey','SG-SF':'purple'}
colors = [colormap[x] for x in data['Pos']]

fig1=figure(title='Age Vs. Log_salary',tools=[hover,'wheel_zoom'])
fig1.xaxis.axis_label = 'Age'
fig1.yaxis.axis_label = 'Log_salary'
fig1.circle(y='logsalary',x={'field':'Age','transform':Jitter(width=1)},source=source, fill_alpha=0.2, size=10,color=colors,legend='Pos')

tab1=Panel(child=fig1,title='Age')

fig2=figure(title='PSG Vs. Log_salary',tools=[hover2,'wheel_zoom'])
fig2.xaxis.axis_label = 'PSG'
fig2.yaxis.axis_label = 'Log_salary'
fig2.circle(y='logsalary',x='PSG',source=source, fill_alpha=0.2, size=10,color=colors,legend='Pos')
tab2=Panel(child=fig2,title='PSG Vs. Log_salary')

tabs=Tabs(tabs=[tab1,tab2])
show(tabs)

# Question 3: Diabetes classification using support vector machines (4+3+3=10 pts) 
(a) Apply a linear SVM, using the scikit-SVM, for the Pima Indian Women diabetes detection problem on the dataset provided (details on dataset here  http://archive.ics.uci.edu/ml/datasets/Pima+Indians+Diabetes) . Specify how you chose the slack cost/penalty (‘C’ parameter)for the model. Maintain all other parameters as default. Hint: http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.GridSearchCV.html will make 10-fold cross-validation easier.
The code to get the training/testing data is provided below.

(b) Repeat (a) but using a Gaussian radial basis kernel.

(c) Summarize the comparative performance (mean error rates) of the classifiers. What do you conclude? (be brief).

In [18]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn import grid_search

data_train = pd.read_csv('diabetes_train-log.csv')
data_test = pd.read_csv('diabetes_test-log.csv')
cols = ['numpreg', 'plasmacon', 'bloodpress', 'skinfold', 'seruminsulin', 'BMI', 'pedigreefunction', 'age']

xtrain = np.asmatrix(data_train[cols])
ytrain = np.asarray(data_train['classvariable']).T

xtest = np.asmatrix(data_test[cols])
ytest = np.asarray(data_test['classvariable']).T

## SOLUTION